### ISSUE TITLE
assessDesign() questions

### ISSUE THREAD

**Issue by mitchell-thomann** [Boehringer-Ingelheim/BayesianMCPMod#11]
Is there a way to assess a design on an effect that doesn't come from a parametric dose-response model (ex: custom effect with a dose-response mean vector as an input)?

Additional criteria to consider for assessDesign():
- Dose-response estimates, raw or placebo adjusted
- Quantile of the posterior distribution, ex: Pr(D_i - D_0) > threshold
- Target dose success or based on credible intervals

**Comment by sebastianbossert** [comment]
Dose-response estimates are now possible via the predict function, related quantiles (based on bootstrap approach) can be calculated via the getBootstrapQuantiles function. The update to also allow placebo-corrected quantiles is planned for the next version. Same applies for the target dose success.
