### ISSUE TITLE
getPosterior() output

### ISSUE THREAD

**Issue by mitchell-thomann** [Boehringer-Ingelheim/BayesianMCPMod#7]
Unable to access the `Summary of Posterior Distributions` table - this would be good output to be able to programmatically access

**Comment by stevegbrooks** [comment]
Great point!

So the call `summary.postList(posteriors_list)` should do the trick, where `posteriors_list` is a "postList" object from `getPosterior()`.

But I can also see that this isn't an obvious thing to the user. Short of refactoring the object's output format, would it be enough to document the availability of `summary.postList()` better?

**Comment by sebastianbossert** [comment]
This is possible via the summary function (so summary(posterior)). We can follow-up whether for a next version this aspect would need to be further extended (cf. also the comment for the prediction).
