### ISSUE TITLE
performBayesianMCP() issues

### ISSUE THREAD

**Issue by mitchell-thomann** [Boehringer-Ingelheim/BayesianMCPMod#8]
- Output is not clear - the default return is success rate and number of sims - however using BMCP_result[1,1:5] you seem to get individual simulation results.  It is not intuitive how to use this information
- For the individual simulation results, I would not call the contrast value evaluation a p-value.  It's confusing and is not a p-value
- Consider adding the contrast critical value in the simulation output so that you can easily see which models are "significant"

**Comment by sebastianbossert** [comment]
Thanks. We modified the output of the function accordingly.
