### ISSUE TITLE
getModelFits() issues/suggestions

### ISSUE THREAD

**Issue by mitchell-thomann** [Boehringer-Ingelheim/BayesianMCPMod#9]
- I assume that this modeling is based on AIC weighting.  I think the weighted probabilities for each model would be of interested to return/plot in addition to the AIC
- Individual dose summaries would be of interest (either candidate doses or interpolated doses) for the model fitting
- Control adjusted summaries would also be of interest (D_i - D_0)
- Ability to specify the quantiles of the CrI would be very useful
- Target dose estimation would also be preferred
- Posterior summaries of the form Pr(D_i > x) or placebo-adjusted summaries of the form Pr(D_i - D_0) is very useful
- Actual samples from the posterior would be of highest interest so that the user can create their own summaries and decision criteria

**Comment by sebastianbossert** [comment]
AIC weights are added to the function output, individual dose summaries can be created via the predict function, control adjusted summaries, target dose estimates and Posterior summaries are planned for the next version (details TBD).
